name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker Image
      run: docker build -t my-app-image .

    - name: Run Container for Testing
      run: |
        docker run -d -p 5000:5000 --name my-app-test my-app-image
        sleep 5
        curl --retry 5 --retry-connrefused http://localhost:5000

    - name: Stop and Remove Container
      run: docker rm -f my-app-test
